### ISSUE TITLE
how to use it in spring?

### ISSUE THREAD

**Issue by softboy99** [simple-java-mail/smtp-connection-pool#2]
Is it appropriate for using in spring?

**Comment by bbottema** [comment]
I can't think of a reason why it wouldn't be.

I'll come up with an example in a few days, when I get my laptop replacement.

**Comment by bbottema** [comment]
Actually the code is just the same for Spring as it is for any application.

```java
@Configuration
public class SmptPoolConfig {
	@Bean
	public SmtpConnectionPool smtpConnectionPool() {
		return yourConnectionPoolInstance; // see GitHub project home for examples
	}
}
```

**Comment by softboy99** [comment]
Hi,
Sorry, for the confusion, In spring boot, the mailsender encapsulate the Transport object createion n DoSend method. So how to use this lib to use the connection pool.

**Comment by bbottema** [comment]
Sorry, but I still don't understand how this is Spring related.
