### ISSUE TITLE
Mail dependency

### ISSUE THREAD

**Issue by karlvr** [simple-java-mail/smtp-connection-pool#3]
I think the `pom.xml` is depending upon the `com.sun` implementation of `jakarta-mail`, whereas we're trying to use the Angus implementation. What do you think about changing the `pom.xml` dependency to:

```xml
<dependency>
    <groupId>jakarta.mail</groupId>
    <artifactId>jakarta.mail-api</artifactId>
    <version>2.1.2</version>
</dependency>
```

**Comment by bbottema** [comment]
I'm not sure about moving it up, just yet. There are some important downstream dependencies to consider. However, I tested smtp-connection-pool with this dependency and it works just fine.

What you can do for now is exclude the jakarta mail dependency and include the Angus one manually.

**Comment by karlvr** [comment]
@bbottema thanks for your comment. I have evolved my thinking to be that libraries should never depend upon any particular implementation of an EE API. Instead the application, or application server, should makes its own decisions about the implementations it uses. That's what inspired my comments! We will manage the dependencies through exclusions and bans in our own applications until such utopian times ;-)
